### ISSUE TITLE
Not giving the correct/ complete LaTeX

### ISSUE THREAD

**Issue by Thiago-Assis-T** [olmobaldoni/logseq-formula-ocr-plugin#1] opened 2024-04-02 00:24 UTC
Hello, i installed the plugin, however it didn't get one single LaTeX formula correctly:
examples: 
image:
![image](https://github.com/olmobaldoni/logseq-formula-ocr-plugin/assets/104371494/1f0ca258-1da6-4dea-af43-df75b95ee47a)
output:
`
$$j(\varepsilon)={\frac{1}{\sigma\sqrt{$$
`
image: 
![image](https://github.com/olmobaldoni/logseq-formula-ocr-plugin/assets/104371494/d4e59472-8180-443b-ab46-a3461c9fdf4c)

output:

`$$v2(g)={\frac{(2-3)^{2$$`

it repeats with simpler or more complex examples... 

I installed the plugin from inside logseq, on nixos-unstable and logseq 0.10.8
feel free to ask more questions and request info.

edit: forgot to put the outputs on code blocks and it didn't render properly

**Comment by olmobaldoni** [comment] 2024-04-02 15:39
Hi! I think the problem is that Nougat is a model obtained from training on classic LaTeX documents, where the mathematical formulas are on a white background.  Since you are inferring images with a black background, this could cause problems.

Do you also have this problem with formula images with a white background?  When I can't get the correct LaTeX code, I generally try to use screenshots of different sizes

If you have any other doubts, don't hesitate to write

**Comment by Thiago-Assis-T** [comment] 2024-04-02 16:38
I didn't think of that, holdup, let me test the hypothesis

**Comment by Thiago-Assis-T** [comment] 2024-04-02 16:42
yeah,kinda the same thing...

![image](https://github.com/olmobaldoni/logseq-formula-ocr-plugin/assets/104371494/4051942e-0744-4dd7-9a8f-7e429dc336a8)

`$$\Delta f=\nabla^{2}f=\nabla\cdot\nabla$$`

![image](https://github.com/olmobaldoni/logseq-formula-ocr-plugin/assets/104371494/428d385f-5a80-4096-9980-831ad7f1c440)

`$$\int_{a}^{b}f^{\prime}(t$$`

now they are just incomplete...

also, the image size thing, doesn't make a difference at all, the results are always the same for the formula, independent of image size...

**Comment by Thiago-Assis-T** [comment] 2024-04-02 18:18
I tried taking a look at hugging face for some logs... found nothing, is there such thing?

**Comment by zhuo121** [comment] 2024-04-08 09:21
I have the same problem, when I copy a long formula, it only shows the first part of the long formula, and the later part does not output properly
![image](https://github.com/olmobaldoni/logseq-formula-ocr-plugin/assets/73180093/21f02702-1f1f-41d0-9264-1a1a3baa6b79)
$${\mathfrak{Z}}_{i}(x_{i}) : =\left\{\sum_{x_{i}^{\$$

**Comment by olmobaldoni** [comment] 2024-04-11 10:48
The author of the model has opened an issue [here](https://github.com/huggingface/huggingface.js/issues/487) in which he reports the problem. It seems that HF's inference API cuts off the answer. The problem is also reported [here](https://github.com/NormXU/nougat-latex-ocr/issues/2)

**Comment by zhuo121** [comment] 2024-04-11 11:09
Thanks a lot. It seems that this problem haven't been solved yet and still need some time.

**Comment by Thiago-Assis-T** [comment] 2024-04-18 02:52
Thanks a lot olmobaldoni for the reply, i'll check the issues you cited

**Comment by olmobaldoni** [comment] 2024-07-10 16:34
After a few months, I found the time to implement a workaround using Docker. It is now possible to run a Docker container that uses the original model without relying on the Hugging Face inference API. I have also made some changes to the commands used in Logseq.

Since the issue with Hugging Face does not appear to have been resolved yet, I will be closing this issue here.

**Closed as completed by olmobaldoni** 2024-07-10 16:34 UTC
